import type { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface Props {
  children: React.ReactNode;
  numberInput: React.ReactNode;
  radioGroup: React.ReactNode;
  homeProduct: React.ReactNode;
  proProduct: React.ReactNode;
  productCode: React.ReactNode;
  betaProduct: React.ReactNode;
}

const CodeInputLayout: React.FC<Props> = ({
  children,
  numberInput,
  radioGroup,
  homeProduct,
  proProduct,
  productCode,
  betaProduct,
}) => {
  return (
    <div className="flex flex-col gap-16 py-4">
      {numberInput}
      {radioGroup}
      {homeProduct}
      {proProduct}
      {betaProduct}
      {productCode}
      <div className="pt-8">{children}</div>
    </div>
  );
};

export default CodeInputLayout;
